<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210130911 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Skaters database';
    }

    public function up(Schema $schema): void
    {

        $this->addSql('CREATE TABLE skater_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, nationality VARCHAR(255) DEFAULT NULL, birthyear INT DEFAULT NULL, favorite_trick VARCHAR(255) DEFAULT NULL, win_sls BOOLEAN DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {

        $this->addSql('DROP TABLE skater_entity');
    }
}
