name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-24.04
    steps:
      -   name: Checkout
          uses: actions/checkout@v4

      -   name: Setup Symfony
          uses: ./.github/workflows/actions/setup/

      -   name: Restore result cache
          uses: actions/cache/restore@v4
          with:
            path: .php-cs-fixer.cache
            key: phpcsfixer-result-cache-${{ github.run_id }}
            restore-keys: |
              phpcsfixer-result-cache-
      -   name: Run PHP-CS-Fixer
          run: vendor/bin/php-cs-fixer fix --dry-run

      -   name: Save result cache
          uses: actions/cache/save@v4
          if: always()
          with:
            path: .php-cs-fixer.cache
            key: phpcsfixer-result-cache-${{ github.run_id }}
